# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67cb11e717765929a136a29beb31a863182bea51c2517ae381c3572547ac25cc394c657a02a513cc1111ece27e527f2cff7b7d7a30fde6f9f85dd0bacc2848a6

test:
  secret_key_base: 5b54e76f74987a52f794ea437085fa159af4afb81e53489e184dd7feae5bf4389f6c83686182ac183bc4fab0df953e2112fa1f8a784fc834d2e5ca4f0436e979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
